repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
-   repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
    -   id: flake8
        exclude: ^(tests/django_app/|docs/)
-   repo: https://github.com/PyCQA/bandit
    rev: 1.9.4
    hooks:
    -   id: bandit
        args: ["--severity-level", "high"]
