# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 10:52
from __future__ import unicode_literals

from django.db import migrations


sql = """
CREATE OR REPLACE FUNCTION add(integer, integer) RETURNS integer
    AS 'select $1 + $2;'
    LANGUAGE SQL
    IMMUTABLE
    RETURNS NULL ON NULL INPUT;
"""


class Migration(migrations.Migration):
    dependencies = []
    operations = [migrations.RunSQL(sql)]
