#
# Copyright (c) 2015-2021 Canonical, Ltd.
#
# This file is part of Talisker
# (see http://github.com/canonical-ols/talisker).
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
"""
This is an internal test tool to construct a requirements.txt with dependencies
pinned to the miniumum supported versions, for use with tox.
"""
import os
import sys
import argparse

from setuptools.config import read_configuration
from pkg_resources import Requirement, parse_requirements


def get_source(comes_from):
    index = comes_from.find(' (line ')
    if index != -1:
        comes_from = comes_from[:index]
    if comes_from.startswith('-r '):
        comes_from = comes_from[3:]
    return comes_from


def print_file(filename, requirements):
    print('# ' + filename)
    for requirement in requirements:
        req = str(requirement)
        specs = [(r.version, r) for r in requirement.specifier]
        if specs:
            version, spec = min(specs)
            if version in spec:
                req = '{}=={}'.format(requirement.name, version)
                marker = getattr(requirement, 'marker', None)
                if marker:
                    req += ';' + str(marker)
            else:
                req += '  # no explicit minimum'
        print(req)
    print()


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("requirements", nargs="*")
    parser.add_argument("--extras", default=[])

    args = parser.parse_args()
    if args.extras:
        args.extras = set(args.extras.split(','))
    options = {}

    print('# AUTOGENERATED by {}\n# DO NOT EDIT\n#\n'.format(sys.argv[0]))

    if os.path.exists('setup.cfg'):
        options = read_configuration('setup.cfg').get('options', {})

    install_requires = options.get('install_requires', [])
    extras_require = options.get('extras_require', {})

    if install_requires:
        fname = 'setup.cfg:options.install_requires'
        print_file(
            fname,
            (Requirement.parse(l) for l in sorted(install_requires)),
        )

    for extra, requires in sorted(extras_require.items()):
        if extra in args.extras:
            fname = 'setup.cfg:options.extras_require:' + extra
            print_file(
                fname,
                (Requirement.parse(l) for l in sorted(requires)),
            )

    for filename in args.requirements:
        print_file(filename, parse_requirements(open(filename)))
